In [76]:
import pandas as pd
df=pd.read_csv(r"C:\Users\maka\OneDrive\Desktop\Assignment_3\dog_intellience\AKC Breed Info.csv")
df

,index,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
0,0,Akita,26,28,80,120
1,1,Anatolian Sheepdog,27,29,100,150
2,2,Bernese Mountain Dog,23,27,85,110
3,3,Bloodhound,24,26,80,120
4,4,Borzoi,26,28,70,100
...,...,...,...,...,...,...
145,145,Papillon,8,11,5,10
146,146,Pomeranian,12,12,3,7
147,147,Poodle Toy,10,10,10,10
148,148,Toy Fox Terrier,10,10,4,7
149,149,Yorkshire Terrier,8,8,3,7

In [77]:
# filling null
breed = df.replace('na', np.NaN)
breed['height_low_inches'] = pd.to_numeric(breed['height_low_inches'], errors='coerce')
breed['height_low_inches'] = round(breed['height_low_inches'].fillna(breed['height_low_inches'].mean()).astype('float'),2)
breed

,index,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
0,0,Akita,26.0,28,80,120
1,1,Anatolian Sheepdog,27.0,29,100,150
2,2,Bernese Mountain Dog,23.0,27,85,110
3,3,Bloodhound,24.0,26,80,120
4,4,Borzoi,26.0,28,70,100
...,...,...,...,...,...,...
145,145,Papillon,8.0,11,5,10
146,146,Pomeranian,12.0,12,3,7
147,147,Poodle Toy,10.0,10,10,10
148,148,Toy Fox Terrier,10.0,10,4,7
149,149,Yorkshire Terrier,8.0,8,3,7

In [79]:
breed2 = breed.replace('na', np.NaN)
breed2['height_high_inches'] = pd.to_numeric(breed2['height_high_inches'], errors='coerce')
breed2['height_high_inches'] = round(breed2['height_high_inches'].fillna(breed2['height_high_inches'].mean()).astype('float'),2)
breed2

,index,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
0,0,Akita,26.0,28.0,80,120
1,1,Anatolian Sheepdog,27.0,29.0,100,150
2,2,Bernese Mountain Dog,23.0,27.0,85,110
3,3,Bloodhound,24.0,26.0,80,120
4,4,Borzoi,26.0,28.0,70,100
...,...,...,...,...,...,...
145,145,Papillon,8.0,11.0,5,10
146,146,Pomeranian,12.0,12.0,3,7
147,147,Poodle Toy,10.0,10.0,10,10
148,148,Toy Fox Terrier,10.0,10.0,4,7
149,149,Yorkshire Terrier,8.0,8.0,3,7

In [80]:
breed3 = breed2.replace('na', np.NaN)
breed3['weight_low_lbs'] = pd.to_numeric(breed3['weight_low_lbs'], errors='coerce')
breed3['weight_low_lbs'] = round(breed3['weight_low_lbs'].fillna(breed3['weight_low_lbs'].mean()).astype('float'),2)
breed3

,index,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
0,0,Akita,26.0,28.0,80.0,120
1,1,Anatolian Sheepdog,27.0,29.0,100.0,150
2,2,Bernese Mountain Dog,23.0,27.0,85.0,110
3,3,Bloodhound,24.0,26.0,80.0,120
4,4,Borzoi,26.0,28.0,70.0,100
...,...,...,...,...,...,...
145,145,Papillon,8.0,11.0,5.0,10
146,146,Pomeranian,12.0,12.0,3.0,7
147,147,Poodle Toy,10.0,10.0,10.0,10
148,148,Toy Fox Terrier,10.0,10.0,4.0,7
149,149,Yorkshire Terrier,8.0,8.0,3.0,7

In [81]:
breed4 = breed3.replace('na', np.NaN)
breed4['weight_high_lbs'] = pd.to_numeric(breed4['weight_high_lbs'], errors='coerce')
breed4['weight_high_lbs'] = round(breed4['weight_high_lbs'].fillna(breed4['weight_high_lbs'].mean()).astype('float'),2)
breed4

,index,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
0,0,Akita,26.0,28.0,80.0,120.0
1,1,Anatolian Sheepdog,27.0,29.0,100.0,150.0
2,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0
3,3,Bloodhound,24.0,26.0,80.0,120.0
4,4,Borzoi,26.0,28.0,70.0,100.0
...,...,...,...,...,...,...
145,145,Papillon,8.0,11.0,5.0,10.0
146,146,Pomeranian,12.0,12.0,3.0,7.0
147,147,Poodle Toy,10.0,10.0,10.0,10.0
148,148,Toy Fox Terrier,10.0,10.0,4.0,7.0
149,149,Yorkshire Terrier,8.0,8.0,3.0,7.0

In [65]:
import pandas as pd
data=pd.read_csv(r"C:\Users\maka\OneDrive\Desktop\Assignment_3\dog_intellience\dog_intelligence.csv")
data

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95%,1,4
1,1,Poodle,Brightest Dogs,95%,1,4
2,2,German Shepherd,Brightest Dogs,95%,1,4
3,3,Golden Retriever,Brightest Dogs,95%,1,4
4,4,Doberman Pinscher,Brightest Dogs,95%,1,4
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100

In [66]:
br = data.replace('na', np.NaN)
br['reps_lower'] = pd.to_numeric(br['reps_lower'], errors='coerce')
br['reps_lower'] = round(br['reps_lower'].fillna(br['reps_lower'].mean()).astype('float'),2)
br

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95%,1.0,4
1,1,Poodle,Brightest Dogs,95%,1.0,4
2,2,German Shepherd,Brightest Dogs,95%,1.0,4
3,3,Golden Retriever,Brightest Dogs,95%,1.0,4
4,4,Doberman Pinscher,Brightest Dogs,95%,1.0,4
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100

In [67]:
br2 = data.replace('na', np.NaN)
br2['reps_upper'] = pd.to_numeric(br2['reps_upper'], errors='coerce')
br2['reps_upper'] = round(br2['reps_upper'].fillna(br2['reps_upper'].mean()).astype('float'),2)
br2

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95%,1,4.0
1,1,Poodle,Brightest Dogs,95%,1,4.0
2,2,German Shepherd,Brightest Dogs,95%,1,4.0
3,3,Golden Retriever,Brightest Dogs,95%,1,4.0
4,4,Doberman Pinscher,Brightest Dogs,95%,1,4.0
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81,100.0
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81,100.0
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81,100.0
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81,100.0
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100.0

In [69]:
br3 = data.replace('na', np.NaN)
br3['obey'] = pd.to_numeric(br3['obey'], errors='coerce')
br3['obey'] = round(br3['obey'].fillna(br3['obey'].mean()).astype('float'),2)
br3

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,NaN,1,4
1,1,Poodle,Brightest Dogs,NaN,1,4
2,2,German Shepherd,Brightest Dogs,NaN,1,4
3,3,Golden Retriever,Brightest Dogs,NaN,1,4
4,4,Doberman Pinscher,Brightest Dogs,NaN,1,4
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100

In [70]:
import pandas as pd
data=pd.read_csv(r"C:\Users\maka\OneDrive\Desktop\Assignment_3\dog_intellience\dog_intelligence.csv")
data

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95%,1,4
1,1,Poodle,Brightest Dogs,95%,1,4
2,2,German Shepherd,Brightest Dogs,95%,1,4
3,3,Golden Retriever,Brightest Dogs,95%,1,4
4,4,Doberman Pinscher,Brightest Dogs,95%,1,4
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100

In [71]:
br3 = data.replace('na', np.NaN)
br3['reps_lower'] = pd.to_numeric(br3['reps_lower'], errors='coerce')
br3['reps_lower'] = round(br3['reps_lower'].fillna(br3['reps_lower'].mean()).astype('float'),2)
br3

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95%,1.0,4
1,1,Poodle,Brightest Dogs,95%,1.0,4
2,2,German Shepherd,Brightest Dogs,95%,1.0,4
3,3,Golden Retriever,Brightest Dogs,95%,1.0,4
4,4,Doberman Pinscher,Brightest Dogs,95%,1.0,4
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100

In [72]:
br4 = br3.replace('na', np.NaN)
br4['reps_upper'] = pd.to_numeric(br4['reps_upper'], errors='coerce')
br4['reps_upper'] = round(br4['reps_upper'].fillna(br4['reps_upper'].mean()).astype('float'),2)
br4

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95%,1.0,4.0
1,1,Poodle,Brightest Dogs,95%,1.0,4.0
2,2,German Shepherd,Brightest Dogs,95%,1.0,4.0
3,3,Golden Retriever,Brightest Dogs,95%,1.0,4.0
4,4,Doberman Pinscher,Brightest Dogs,95%,1.0,4.0
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100.0
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100.0
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100.0
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100.0
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81.0,100.0

In [73]:
br4['obey'] = br4['obey'].replace('%','', regex=True)
br4['obey'] = pd.to_numeric(br4['obey'],errors='coerce')
br4['obey']=br4['obey'].fillna(br4['obey'].mean())
br4

,index,Breed,Classification,obey,reps_lower,reps_upper
0,0,Border Collie,Brightest Dogs,95.00,1.0,4.0
1,1,Poodle,Brightest Dogs,95.00,1.0,4.0
2,2,German Shepherd,Brightest Dogs,95.00,1.0,4.0
3,3,Golden Retriever,Brightest Dogs,95.00,1.0,4.0
4,4,Doberman Pinscher,Brightest Dogs,95.00,1.0,4.0
...,...,...,...,...,...,...
131,131,Borzoi,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0
132,132,Chow Chow,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0
133,133,Bulldog,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0
134,134,Basenji,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0
135,135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0

In [97]:
pd.merge(breed4,br4,on='Breed',how='inner').to_csv('dog_info_combined.csv') #merge & save file
df=pd.read_csv(r"C:\Users\maka\OneDrive\Desktop\Assignment_3\dog_info_combined.csv")
df

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,142,Japanese Chin,8.0,11.0,4.0,11.0,115,Fair Working/Obedience Intelligence,30.00,41.0,80.0
101,101,143,Maltese,8.0,10.0,4.0,6.0,109,Fair Working/Obedience Intelligence,30.00,41.0,80.0
102,102,145,Papillon,8.0,11.0,5.0,10.0,7,Brightest Dogs,95.00,1.0,4.0
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.00,16.0,25.0

In [174]:
diff = len(df['Classification'].unique())
print( diff,'different classifications')

6 different classifications

In [108]:
breeds=df['Classification'].unique().tolist()
breeds
breed=df.groupby('Classification')['Breed'].count()
print('Most',breed.idxmax(),':',breed.max())
print('Leasts',breed.idxmin(),':',breed.min())

Most Average Working/Obedience Intelligence : 34
Leasts Brightest Dogs : 7

In [117]:
height = ((df['height_low_inches'] + df['height_high_inches'])/2)
print("Avg height:",height)
print("tallest:",height.idxmin(),"shortest:", height.min())
weight = ((df['weight_low_lbs'] + df['weight_high_lbs'])/2)
print("Avg weight:",weight)
print("heaviest:",weight.idxmin(),"lightest:", weight.min())

Avg height: 0      27.0
1      25.0
2      25.0
3      27.0
4      26.0
       ...
100     9.5
101     9.0
102     9.5
103    12.0
104     8.0
Length: 105, dtype: float64
tallest: 97 shortest: 7.5
Avg weight: 0      100.0
1       97.5
2      100.0
3       85.0
4      115.0
       ...
100      7.5
101      5.0
102      7.5
103      5.0
104      5.0
Length: 105, dtype: float64
heaviest: 97 lightest: 3.5

In [131]:
df

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,142,Japanese Chin,8.0,11.0,4.0,11.0,115,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0
101,101,143,Maltese,8.0,10.0,4.0,6.0,109,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0
102,102,145,Papillon,8.0,11.0,5.0,10.0,7,Brightest Dogs,95.00,1.0,4.0,3.0,3.0
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0

In [136]:
df['variability_height'] = round((df['height_high_inches']-df['height_low_inches']))
df['variability_weight'] = round((df['weight_high_lbs']-df['weight_low_lbs']))
df

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,40.0
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,4.0,25.0
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,40.0
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,30.0
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,142,Japanese Chin,8.0,11.0,4.0,11.0,115,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,3.0,7.0
101,101,143,Maltese,8.0,10.0,4.0,6.0,109,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,2.0
102,102,145,Papillon,8.0,11.0,5.0,10.0,7,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,3.0,5.0
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,0.0,4.0
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,0.0,4.0

In [137]:
df['variability_reps'] = round((df['reps_upper']-df['reps_lower']))
df

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,40.0
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,4.0,25.0
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,40.0
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,30.0
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,142,Japanese Chin,8.0,11.0,4.0,11.0,115,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,3.0,7.0
101,101,143,Maltese,8.0,10.0,4.0,6.0,109,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,2.0
102,102,145,Papillon,8.0,11.0,5.0,10.0,7,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,3.0,5.0
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,0.0,4.0
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,0.0,4.0

In [142]:
df['rank_height'] = df['variability_height'].rank()
df.sort_values('rank_height')
df['rank_weight'] = df['variability_weight'].rank()
df.sort_values('rank_weight')
df['rank_reps'] = df['variability_reps'].rank()
df

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,40.0,36.0,99.5,62.5
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,4.0,25.0,84.0,87.5,38.5
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,40.0,36.0,99.5,84.0
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,30.0,36.0,91.5,84.0
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,30.0,36.0,91.5,97.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,142,Japanese Chin,8.0,11.0,4.0,11.0,115,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,3.0,7.0,62.0,38.0,97.0
101,101,143,Maltese,8.0,10.0,4.0,6.0,109,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,2.0,36.0,9.0,97.0
102,102,145,Papillon,8.0,11.0,5.0,10.0,7,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,3.0,5.0,62.0,30.5,4.0
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,0.0,4.0,7.0,22.0,38.5
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,0.0,4.0,7.0,22.0,19.5

In [145]:
highest_height=df.sort_values('rank_height',ascending=False).drop_duplicates('rank_height')
highest_height

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
66,66,96,Vizsla,48.0,66.0,22.0,25.0,29,Excellent Working Dogs,85.0,5.0,15.0,10.0,10.0,18.0,3.0,105.0,15.0,38.5
54,54,77,Irish Water Spaniel,10.0,23.0,45.0,65.0,28,Excellent Working Dogs,85.0,5.0,15.0,10.0,10.0,13.0,20.0,104.0,79.5,38.5
52,52,75,Ibizan Hound,22.0,29.0,42.0,55.0,98,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,7.0,13.0,102.0,60.0,62.5
80,80,113,Dandie Dinmont Terrier,18.0,24.0,8.0,11.0,112,Fair Working/Obedience Intelligence,30.0,41.0,80.0,39.0,39.0,6.0,3.0,100.0,15.0,97.0
51,51,73,Finnish Spitz,15.0,20.0,31.0,35.0,69,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,5.0,4.0,95.5,22.0,62.5
95,95,137,Whippet,18.0,22.0,27.0,30.0,94,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,4.0,3.0,84.0,15.0,62.5
38,38,55,American Water Spaniel,15.0,18.0,25.0,45.0,74,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,3.0,20.0,62.0,79.5,62.5
86,86,126,Scottish Terrier,10.0,12.0,18.0,22.0,119,Fair Working/Obedience Intelligence,30.0,41.0,80.0,39.0,39.0,2.0,4.0,36.0,22.0,97.0
45,45,63,Bull Terrier,21.0,22.0,50.0,70.0,121,Fair Working/Obedience Intelligence,30.0,41.0,80.0,39.0,39.0,1.0,20.0,19.0,79.5,97.0
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.0,5.0,15.0,10.0,10.0,0.0,4.0,7.0,22.0,38.5

In [146]:
lowest_height=df.sort_values('rank_height').drop_duplicates('rank_height')
lowest_height

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.0,16.0,25.0,9.0,9.0,0.0,4.0,7.0,22.0,19.5
57,57,80,Norwegian Elkhound,19.0,20.0,40.0,60.0,52,Above Average Working Dogs,70.0,16.0,25.0,9.0,9.0,1.0,20.0,19.0,79.5,19.5
46,46,65,Chinese Shar Pei,18.0,20.0,45.0,55.0,95,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,2.0,10.0,36.0,49.5,62.5
24,24,34,English Foxhound,22.0,25.0,65.0,70.0,79,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,3.0,5.0,62.0,30.5,62.5
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.0,5.0,15.0,10.0,10.0,4.0,25.0,84.0,87.5,38.5
78,78,110,Cavalier King Charles Spaniel,10.0,15.0,15.0,20.0,71,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,5.0,5.0,95.5,30.5,62.5
80,80,113,Dandie Dinmont Terrier,18.0,24.0,8.0,11.0,112,Fair Working/Obedience Intelligence,30.0,41.0,80.0,39.0,39.0,6.0,3.0,100.0,15.0,97.0
7,7,9,Irish Wolfhound,28.0,35.0,90.0,150.0,65,Average Working/Obedience Intelligence,50.0,26.0,40.0,14.0,14.0,7.0,60.0,102.0,104.0,62.5
54,54,77,Irish Water Spaniel,10.0,23.0,45.0,65.0,28,Excellent Working Dogs,85.0,5.0,15.0,10.0,10.0,13.0,20.0,104.0,79.5,38.5
66,66,96,Vizsla,48.0,66.0,22.0,25.0,29,Excellent Working Dogs,85.0,5.0,15.0,10.0,10.0,18.0,3.0,105.0,15.0,38.5

In [147]:
lowest_weight=df.sort_values('rank_weight').drop_duplicates('rank_weight')
lowest_weight

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
43,43,60,Border Collie,19.0,21.0,40.0,40.0,0,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,2.0,0.0,36.0,2.5,4.0
93,93,135,Welsh Terrier,15.0,15.0,20.0,21.0,99,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,0.0,1.0,7.0,5.0,62.5
82,82,120,Lakeland Terrier,13.0,14.0,15.0,17.0,116,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,1.0,2.0,19.0,9.0,97.0
66,66,96,Vizsla,48.0,66.0,22.0,25.0,29,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,18.0,3.0,105.0,15.0,38.5
96,96,138,Affenpinscher,9.0,12.0,8.0,12.0,53,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,3.0,4.0,62.0,22.0,19.5
28,28,39,Giant Schnauzer,25.0,28.0,70.0,75.0,34,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,3.0,5.0,62.0,30.5,19.5
85,85,125,Schipperke,10.0,13.0,12.0,18.0,14,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,3.0,6.0,62.0,35.5,38.5
89,89,130,Shih Tzu,8.0,11.0,9.0,16.0,125,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,3.0,7.0,62.0,38.0,84.0
83,83,123,Pug,10.0,11.0,14.0,22.0,106,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,1.0,8.0,19.0,40.5,97.0
49,49,70,English Springer Spaniel,20.0,20.0,45.0,55.0,12,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,0.0,10.0,7.0,49.5,38.5
81,81,117,French Bulldog,11.0,12.0,17.0,28.0,107,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,1.0,11.0,19.0,58.0,97.0
71,71,102,Beagle,13.0,16.0,18.0,30.0,128,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,3.0,12.0,62.0,59.0,84.0
52,52,75,Ibizan Hound,22.0,29.0,42.0,55.0,98,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,7.0,13.0,102.0,60.0,62.5
36,36,52,Weimaraner,25.0,27.0,70.0,85.0,24,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,2.0,15.0,36.0,66.5,38.5
79,79,112,Dachshund,7.0,10.0,16.0,32.0,90,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,3.0,16.0,62.0,73.0,62.5
60,60,87,Portuguese Water Dog,20.0,23.0,42.0,60.0,35,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,3.0,18.0,62.0,74.0,19.5
20,20,29,Chesapeake Bay Retriever,21.0,26.0,55.0,75.0,31,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,5.0,20.0,95.5,79.5,19.5
59,59,85,Pointer,21.0,24.0,44.0,66.0,70,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,3.0,22.0,62.0,85.0,62.5
6,6,7,Great Pyrenees,27.0,32.0,95.0,120.0,118,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,5.0,25.0,95.5,87.5,97.0
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,30.0,36.0,91.5,97.0
25,25,35,English Setter,23.0,27.0,45.0,80.0,56,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,4.0,35.0,84.0,95.5,19.5
23,23,33,Doberman Pinscher,26.0,28.0,60.0,100.0,4,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,2.0,40.0,36.0,99.5,4.0
10,10,13,Newfoundland,26.0,28.0,100.0,150.0,44,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,2.0,50.0,36.0,102.5,19.5
7,7,9,Irish Wolfhound,28.0,35.0,90.0,150.0,65,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,7.0,60.0,102.0,104.0,62.5
12,12,16,Saint Bernard,25.0,28.0,110.0,190.0,120,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,3.0,80.0,62.0,105.0,97.0

In [148]:
highest_weight=df.sort_values('rank_weight',ascending=False).drop_duplicates('rank_weight')
highest_weight

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
12,12,16,Saint Bernard,25.0,28.0,110.0,190.0,120,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,3.0,80.0,62.0,105.0,97.0
7,7,9,Irish Wolfhound,28.0,35.0,90.0,150.0,65,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,7.0,60.0,102.0,104.0,62.5
10,10,13,Newfoundland,26.0,28.0,100.0,150.0,44,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,2.0,50.0,36.0,102.5,19.5
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,40.0,36.0,99.5,62.5
30,30,41,Gordon Setter,23.0,27.0,45.0,80.0,47,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,4.0,35.0,84.0,95.5,19.5
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,30.0,36.0,91.5,97.0
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,4.0,25.0,84.0,87.5,38.5
59,59,85,Pointer,21.0,24.0,44.0,66.0,70,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,3.0,22.0,62.0,85.0,62.5
38,38,55,American Water Spaniel,15.0,18.0,25.0,45.0,74,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,3.0,20.0,62.0,79.5,62.5
60,60,87,Portuguese Water Dog,20.0,23.0,42.0,60.0,35,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,3.0,18.0,62.0,74.0,19.5
79,79,112,Dachshund,7.0,10.0,16.0,32.0,90,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,3.0,16.0,62.0,73.0,62.5
55,55,78,Keeshond,17.0,19.0,35.0,50.0,17,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,2.0,15.0,36.0,66.5,38.5
52,52,75,Ibizan Hound,22.0,29.0,42.0,55.0,98,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,7.0,13.0,102.0,60.0,62.5
71,71,102,Beagle,13.0,16.0,18.0,30.0,128,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,3.0,12.0,62.0,59.0,84.0
81,81,117,French Bulldog,11.0,12.0,17.0,28.0,107,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,1.0,11.0,19.0,58.0,97.0
46,46,65,Chinese Shar Pei,18.0,20.0,45.0,55.0,95,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,10.0,36.0,49.5,62.5
73,73,104,Bichon Frise,9.5,11.5,10.0,18.0,76,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,8.0,36.0,40.5,62.5
89,89,130,Shih Tzu,8.0,11.0,9.0,16.0,125,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,3.0,7.0,62.0,38.0,84.0
85,85,125,Schipperke,10.0,13.0,12.0,18.0,14,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,3.0,6.0,62.0,35.5,38.5
24,24,34,English Foxhound,22.0,25.0,65.0,70.0,79,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,3.0,5.0,62.0,30.5,62.5
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,0.0,4.0,7.0,22.0,38.5
95,95,137,Whippet,18.0,22.0,27.0,30.0,94,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,4.0,3.0,84.0,15.0,62.5
70,70,101,Basenji,17.0,17.0,20.0,22.0,134,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,0.0,2.0,7.0,9.0,84.0
93,93,135,Welsh Terrier,15.0,15.0,20.0,21.0,99,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,0.0,1.0,7.0,5.0,62.5
65,65,94,Standard Schnauzer,17.0,19.0,33.0,33.0,21,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,2.0,0.0,36.0,2.5,38.5

In [149]:
highest_rep=df.sort_values('rank_reps',ascending=False).drop_duplicates('rank_reps')
highest_rep

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
87,87,127,Sealyham Terrier,12.0,12.0,18.0,20.0,105,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,0.0,2.0,7.0,9.0,97.0
89,89,130,Shih Tzu,8.0,11.0,9.0,16.0,125,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,3.0,7.0,62.0,38.0,84.0
53,53,76,Irish Terrier,18.0,19.0,25.0,27.0,100,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,1.0,2.0,19.0,9.0,62.5
65,65,94,Standard Schnauzer,17.0,19.0,33.0,33.0,21,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,2.0,0.0,36.0,2.5,38.5
96,96,138,Affenpinscher,9.0,12.0,8.0,12.0,53,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,3.0,4.0,62.0,22.0,19.5
29,29,40,Golden Retriever,21.0,24.0,55.0,75.0,3,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,3.0,20.0,62.0,79.5,4.0

In [150]:
lowest_rep=df.sort_values('rank_reps').drop_duplicates('rank_reps')
lowest_rep

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps
29,29,40,Golden Retriever,21.0,24.0,55.0,75.0,3,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,3.0,20.0,62.0,79.5,4.0
62,62,90,Samoyed,19.0,24.0,50.0,65.0,42,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,5.0,15.0,95.5,66.5,19.5
17,17,22,Belgian Sheepdog,22.0,26.0,60.0,75.0,15,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,4.0,15.0,84.0,66.5,38.5
75,75,106,Boston Terrier,14.0,15.0,15.0,25.0,101,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,1.0,10.0,19.0,49.5,62.5
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,40.0,36.0,99.5,84.0
86,86,126,Scottish Terrier,10.0,12.0,18.0,22.0,119,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,4.0,36.0,22.0,97.0

In [162]:
obey_avg = df.groupby('Classification')['obey'].mean()
print("Avg of Obey",obey_avg )

Avg of Obey Classification
Above Average Working Dogs                          70.00
Average Working/Obedience Intelligence              50.00
Brightest Dogs                                      95.00
Excellent Working Dogs                              85.00
Fair Working/Obedience Intelligence                 30.00
Lowest Degree of Working/Obedience Intelligence     60.76
Name: obey, dtype: float64

In [155]:
obey_std = df.groupby('Classification')['obey'].std()
print('St Dev of Obey',obey_std)

Standard Deviation of Obey Classification
Above Average Working Dogs                          0.0
Average Working/Obedience Intelligence              0.0
Brightest Dogs                                      0.0
Excellent Working Dogs                              0.0
Fair Working/Obedience Intelligence                 0.0
Lowest Degree of Working/Obedience Intelligence     0.0
Name: obey, dtype: float64

In [158]:
repslower_avg = df.groupby('Classification')['reps_lower'].mean()
print('Avg of Reps_lower',repslower_avg)
repslower_std = df.groupby('Classification')['reps_lower'].std()
print('St Dev of Obey',repslower_std )
repshigher_avg = df.groupby('Classification')['reps_upper'].mean()
print('Avg of Reps higher',repshigher_avg )
reps_high_std = df.groupby('Classification')['reps_upper'].std()
print('St Dev of reps high', reps_high_std)

Average of Reps_lower Classification
Above Average Working Dogs                          16.0
Average Working/Obedience Intelligence              26.0
Brightest Dogs                                       1.0
Excellent Working Dogs                               5.0
Fair Working/Obedience Intelligence                 41.0
Lowest Degree of Working/Obedience Intelligence     81.0
Name: reps_lower, dtype: float64
Standard Deviation of Obey Classification
Above Average Working Dogs                          0.0
Average Working/Obedience Intelligence              0.0
Brightest Dogs                                      0.0
Excellent Working Dogs                              0.0
Fair Working/Obedience Intelligence                 0.0
Lowest Degree of Working/Obedience Intelligence     0.0
Name: reps_lower, dtype: float64
Average of Reps higher Classification
Above Average Working Dogs                           25.0
Average Working/Obedience Intelligence               40.0
Brightest Dogs                                        4.0
Excellent Working Dogs                               15.0
Fair Working/Obedience Intelligence                  80.0
Lowest Degree of Working/Obedience Intelligence     100.0
Name: reps_upper, dtype: float64
Standard Deviation of reps high Classification
Above Average Working Dogs                          0.0
Average Working/Obedience Intelligence              0.0
Brightest Dogs                                      0.0
Excellent Working Dogs                              0.0
Fair Working/Obedience Intelligence                 0.0
Lowest Degree of Working/Obedience Intelligence     0.0
Name: reps_upper, dtype: float64

In [168]:
all_avg = round(df['obey'].mean(),2)
print("Avg of all breeds: ",all_avg)
all_std = round(df['obey'].std(),2)
print('St Dev of all: ',all_std)
reps_lower_avg = round(df['reps_lower'].mean(),2)
print('Avg of Reps_lower: ',reps_lower_avg )
reps_lower_std = round(df['reps_lower'].std(),2)
print('St dev of Reps_lower: ',reps_lower_std)
reps_higher_avg = round(df['reps_upper'].mean(),2)
print('Avg of Reps_higher ',reps_higher_avg)
reps_higher_std = round(df['reps_upper'].std(),2)
print('St dev of Reps_higher: ',reps_higher_std)

Avg of all breeds:  59.92
St Dev of all:  19.22
Avg of Reps_lower:  26.39
St dev of Reps_lower:  20.56
Avg of Reps_higher  42.46
St dev of Reps_higher:  28.11

In [169]:
df['avg_reps'] = (df['reps_upper']+df['reps_lower'])/2
df

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps,avg_reps
0,0,0,Akita,26.0,28.0,80.0,120.0,102,Average Working/Obedience Intelligence,50.00,26.0,40.0,14.0,14.0,2.0,40.0,36.0,99.5,62.5,33.0
1,1,2,Bernese Mountain Dog,23.0,27.0,85.0,110.0,26,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,4.0,25.0,84.0,87.5,38.5,10.0
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,40.0,36.0,99.5,84.0,90.5
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,30.0,36.0,91.5,84.0,90.5
4,4,5,Bullmastiff,25.0,27.0,100.0,130.0,124,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,30.0,36.0,91.5,97.0,60.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,142,Japanese Chin,8.0,11.0,4.0,11.0,115,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,3.0,7.0,62.0,38.0,97.0,60.5
101,101,143,Maltese,8.0,10.0,4.0,6.0,109,Fair Working/Obedience Intelligence,30.00,41.0,80.0,39.0,39.0,2.0,2.0,36.0,9.0,97.0,60.5
102,102,145,Papillon,8.0,11.0,5.0,10.0,7,Brightest Dogs,95.00,1.0,4.0,3.0,3.0,3.0,5.0,62.0,30.5,4.0,2.5
103,103,146,Pomeranian,12.0,12.0,3.0,7.0,27,Excellent Working Dogs,85.00,5.0,15.0,10.0,10.0,0.0,4.0,7.0,22.0,38.5,10.0
104,104,149,Yorkshire Terrier,8.0,8.0,3.0,7.0,33,Above Average Working Dogs,70.00,16.0,25.0,9.0,9.0,0.0,4.0,7.0,22.0,19.5,20.5

In [172]:
df.nlargest(5,'avg_reps')

,Unnamed: 0,index_x,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps,avg_reps
2,2,3,Bloodhound,24.0,26.0,80.0,120.0,130,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,40.0,36.0,99.5,84.0,90.5
3,3,4,Borzoi,26.0,28.0,70.0,100.0,131,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,30.0,36.0,91.5,84.0,90.5
9,9,11,Mastiff,27.0,30.0,175.0,190.0,127,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,3.0,15.0,62.0,66.5,84.0,90.5
13,13,17,Afghan Hound,25.0,27.0,50.0,60.0,135,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,2.0,10.0,36.0,49.5,84.0,90.5
41,41,58,Basset Hound,14.0,14.0,40.0,50.0,126,Lowest Degree of Working/Obedience Intelligence,60.76,81.0,100.0,19.0,19.0,0.0,10.0,7.0,49.5,84.0,90.5

In [171]:
round(df['avg_reps'].mean(),2)

34.42

In [173]:
df.corr()

C:\Users\maka\AppData\Local\Temp\ipykernel_42372\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,Unnamed: 0,index_x,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,obey,reps_lower,reps_upper,Variability_reps,variability_reps,variability_height,variability_weight,rank_height,rank_weight,rank_reps,avg_reps
Unnamed: 0,1.000000,0.999547,-0.750846,-0.679769,-0.853815,-0.851694,0.110935,-0.228851,0.025547,0.125777,0.279414,0.279414,-0.160818,-0.611206,-0.252137,-0.639515,0.175383,0.084493
index_x,0.999547,1.000000,-0.749065,-0.678353,-0.852532,-0.850399,0.113350,-0.232065,0.028299,0.128600,0.281527,0.281527,-0.161087,-0.610247,-0.254571,-0.639348,0.178375,0.087321
height_low_inches,-0.750846,-0.749065,1.000000,0.960425,0.736868,0.729659,-0.106722,0.180179,-0.072870,-0.144387,-0.237645,-0.237645,0.395743,0.511967,0.292203,0.493086,-0.142979,-0.115625
height_high_inches,-0.679769,-0.678353,0.960425,1.000000,0.657195,0.655044,-0.149985,0.206313,-0.123116,-0.182871,-0.242151,-0.242151,0.635881,0.468821,0.491062,0.464177,-0.154443,-0.159630
weight_low_lbs,-0.853815,-0.852532,0.736868,0.657195,1.000000,0.960718,-0.004935,0.109074,0.057446,-0.010833,-0.137914,-0.137914,0.125076,0.610623,0.219204,0.592357,-0.054073,0.018243
weight_high_lbs,-0.851694,-0.850399,0.729659,0.655044,0.960718,1.000000,-0.003513,0.085425,0.042638,-0.015841,-0.122717,-0.122717,0.137956,0.806415,0.229311,0.748917,-0.053154,0.008978
index_y,0.110935,0.113350,-0.106722,-0.149985,-0.004935,-0.003513,1.000000,-0.840573,0.875480,0.923936,0.739673,0.739673,-0.198779,0.000587,-0.179168,-0.070488,0.887091,0.914952
obey,-0.228851,-0.232065,0.180179,0.206313,0.109074,0.085425,-0.840573,1.000000,-0.562981,-0.732019,-0.835400,-0.835400,0.180960,0.011263,0.132892,0.119107,-0.853807,-0.669004
reps_lower,0.025547,0.028299,-0.072870,-0.123116,0.057446,0.042638,0.875480,-0.562981,1.000000,0.948862,0.567035,0.567035,-0.204011,-0.000741,-0.184463,-0.039877,0.748619,0.982807
reps_upper,0.125777,0.128600,-0.144387,-0.182871,-0.010833,-0.015841,0.923936,-0.732019,0.948862,1.000000,0.798070,0.798070,-0.202867,-0.022134,-0.197140,-0.095294,0.878935,0.990836
Variability_reps,0.279414,0.281527,-0.237645,-0.242151,-0.137914,-0.122717,0.739673,-0.835400,0.567035,0.798070,1.000000,1.000000,-0.139919,-0.056337,-0.162286,-0.172526,0.864399,0.709369
variability_reps,0.279414,0.281527,-0.237645,-0.242151,-0.137914,-0.122717,0.739673,-0.835400,0.567035,0.798070,1.000000,1.000000,-0.139919,-0.056337,-0.162286,-0.172526,0.864399,0.709369
variability_height,-0.160818,-0.161087,0.395743,0.635881,0.125076,0.137956,-0.198779,0.180960,-0.204011,-0.202867,-0.139919,-0.139919,1.000000,0.127156,0.809428,0.164178,-0.113024,-0.205936
variability_weight,-0.611206,-0.610247,0.511967,0.468821,0.610623,0.806415,0.000587,0.011263,-0.000741,-0.022134,-0.056337,-0.056337,0.127156,1.000000,0.187310,0.874916,-0.036408,-0.013262
rank_height,-0.252137,-0.254571,0.292203,0.491062,0.219204,0.229311,-0.179168,0.132892,-0.184463,-0.197140,-0.162286,-0.162286,0.809428,0.187310,1.000000,0.267666,-0.134240,-0.194223
rank_weight,-0.639515,-0.639348,0.493086,0.464177,0.592357,0.748917,-0.070488,0.119107,-0.039877,-0.095294,-0.172526,-0.172526,0.164178,0.874916,0.267666,1.000000,-0.123246,-0.072796
rank_reps,0.175383,0.178375,-0.142979,-0.154443,-0.054073,-0.053154,0.887091,-0.853807,0.748619,0.878935,0.864399,0.864399,-0.113024,-0.036408,-0.134240,-0.123246,1.000000,0.834356
avg_reps,0.084493,0.087321,-0.115625,-0.159630,0.018243,0.008978,0.914952,-0.669004,0.982807,0.990836,0.709369,0.709369,-0.205936,-0.013262,-0.194223,-0.072796,0.834356,1.000000