<a href="https://colab.research.google.com/github/makaronaaa/DataSciencePython/blob/main/GaussianNaiveBayesianClassi%0Cer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import seaborn as sb
from sklearn import metrics
data=pd.read_csv('/content/sample_data/GOLD_weekly_return_volatility_labeled.csv')
data

     Year  Week_Number  mean_return  volatility  label
0    2020            1     -0.77360    1.874892    red
1    2020            2      0.12240    1.644458  green
2    2020            3      1.04625    1.093152  green
3    2020            4     -0.18800    1.981426    red
4    2020            5     -0.35180    1.341252    red
..    ...          ...          ...         ...    ...
99   2021           48     -0.98360    1.341614    red
100  2021           49     -0.28920    1.481579    red
101  2021           50      0.50560    2.269345  green
102  2021           51      0.24450    0.447162  green
103  2021           52      0.34175    1.361570  green

[104 rows x 5 columns]

In [10]:
X_train = data[["mean_return","volatility"]][data["Year"]==2020].values
Y_train = data[["label"]][data["Year"]==2020].values

df = data[data["Year"]==2021].reset_index(drop=True)
X_test = df[["mean_return","volatility"]]
Y_test = df["label"]

In [17]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, Y_train).predict(X_test)
accuracy = round(100*np.mean(y_pred == Y_test) , 2)
print("GNB Accuracy Year2: ", accuracy, "%")

GNB Accuracy Year2:  76.92 %

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [20]:
cf = confusion_matrix(Y_test , y_pred)
print("confusion matrix: considering green is + \n",  cf)   
tp = cf[0][0]
fn = cf[0][1]
fp = cf[1][0]
tn = cf[1][1]
print("TP=", tp,"    FP=",  fp,"    FN=",  fn,"   TN=",  tn)

tpr = tp / (tp + fn)
tnr = tn / (tn + fp)
acc = (tp + tn) / (tp + tn + fp + fn)
print("TPR=", tpr, "    TNR=", tnr, "    ACC=", acc)

confusion matrix: considering green is +
 [[23  0]
 [12 17]]
TP= 23     FP= 12     FN= 0    TN= 17
TPR= 1.0     TNR= 0.5862068965517241     ACC= 0.7692307692307693

In [24]:
df["gnb"] = y_pred
df[ :4]

   Year  Week_Number  mean_return  volatility  label    gnb
0  2021            1      1.09480    4.290113  green  green
1  2021            2     -0.69560    1.273715    red    red
2  2021            3      0.36125    1.337281    red  green
3  2021            4     -0.92480    2.726894    red    red

In [25]:
# BUY & HOLD stgy
value = 100
for i in range(len(df)):
    value = round(value*(100 + df['mean_return'][i])/100, 2)
        
print("Final value of portfolio after BUY AND HOLD for year-2: $", value)    
print("annual return = ", round((value-100), 2), '%')

Final value of portfolio after BUY AND HOLD for year-2: $ 96.82
annual return =  -3.18 %

In [28]:
#TRADING BY GNB PREDICTED LABELS for Year 2
value = 100
for i in range(len(df)):
    if df['gnb'][i] == 'green':
        value = round(value*(100 + df['mean_return'][i])/100, 2)
        
print("Final Value of Portfolio after trading  ", value)    
print("annual return = ", round((value-100), 2), '%')

Final Value of Portfolio after trading   116.6
annual return =  16.6 %